spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3309/calculator?serverTimezone=UTC
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-prod.yaml

server:
  port: 9001